(function(root){
	var dev = {};

	dev.pokemon = {
		ninetales : {
			name : {
				en: "Ninetales",
				jap: "Kyukon",
			},
			localNum : {
				red : "38",
				blue : "38",
				yellow : "38",
				gold : "126",
				silver : "126",
				crystal : "126",
				ruby : "154",
				sapphire : "154",
				fireRed : "38",
				leafGreen : "38",
				emerald : "154",
				dimond : null,
				pearl : null,
				platinum : null,
				heartGold : "128",
				soulSilver : "128",
				black : null,
				white : null,
				black2 : "249",
				white2 : "249",
				x : null,
				y : null,
				omegaRuby : "161",
				alphaSapphire : "161",
			},
			basic : {
				nationalNum : "38",
				species : "Fox Pokemon",
				height : "1.09 m",
				weight : "19.9 kg",
			},
			breeding : {
				eggGroup : "Field",
				eggCycle : "21",
				genders : {
					male : "25",
					female : "75",
				},
			},
			training : {
				evs : {
					hp : null,
					attack : null,
					defense : null,
					spAttack : null,
					spDefense : 1,
					speed : 1,
				},
				catchRate : "75",
				happiness : "70",
				exp : "178",
				growthRate : "Medium Fast",
			},
			battle : {
				types : {
					primaryType : "fire",
					secondaryType : null,	
				},
				abilities : {
					firstAbility : "flashFire",
					secondAbility : null,
					hiddenAbility : "drought",
				},
			},
			pokedex : {
				red : "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
				blue : "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
				yellow : "According to an enduring legend, 9 noble saints were united and reincarnated as this POKéMON.",
				gold : "Some legends claim that each of its nine tails has its own unique type of special mystical power.",
				silver : "Its nine beautiful tails are filled with a wondrous energy that could keep it alive for 1,000 years.",
				crystal : "It is said to live a thousand years, and each of its tails is loaded with supernatural powers.",
				ruby : "NINETALES casts a sinister light from its bright red eyes to gain total control over its foe’s mind. This POKéMON is said to live for a thousand years.",
				sapphire : "Legend has it that NINETALES came into being when nine wizards possessing sacred powers merged into one. This POKéMON is highly intelligent - it can understand human speech.",
				fireRed : "It has nine long tails and fur that gleams gold. It is said to live for 1,000 years.",
				leafGreen : "Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse.",
				emerald : "It has long been said that each of the nine tails embody an enchanted power. A long-lived NINETALES will have fur that shines like gold.",
				dimond : "Its nine tails are said to be imbued with a mystic power. It can live for a thousand years.",
				pearl : "Its nine tails are said to be imbued with a mystic power. It can live for a thousand years.",
				platinum : "Its nine tails are said to be imbued with a mystic power. It can live for a thousand years.",
				heartGold : "Some legends claim that each of its nine tails has its own unique type of special mystical power.",
				soulSilver : "Its nine beautiful tails are filled with a wondrous energy that could keep it alive for 1,000 years.",
				black : "Its nine tails are said to be imbued with a mystic power. It can live for a thousand years.",
				white : "Its nine tails are said to be imbued with a mystic power. It can live for a thousand years.",
				black2 : "Each of its nine tails is imbued with supernatural power, and it can live for a thousand years.",
				white2 : "Each of its nine tails is imbued with supernatural power, and it can live for a thousand years.",
				x : "It has nine long tails and fur that gleams gold. It is said to live for 1,000 years.",
				y : "Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse.",
			},
			base : {
				hp : 73,
				attack : 76,
				defense : 75,
				spAttack : 81,
				spDefense : 100,
				speed : 100,
			},
			img : {
				url: ["./res/img/ninetales/Ninetales.png", "./res/img/ninetales/Ninetales.gif"],
			},
			moves : {
				all : ["flamethrower","extrasensory","heatWave","confuseRay","imprison","nastyPlot","quickAttack","safeguard"],
				level : ["flamethrower","confuseRay","imprison","nastyPlot","quickAttack","safeguard"],
				egg : ["extrasensory","heatWave"],
				tutor : ["heatWave"],
				preEvolution : ["extrasensory"],
				hm : [],
				tm : ["flamethrower","safeguard"],
				transfer : [],
			},
		}
	}
	dev.moves = {
		flamethrower : {
			name : "Flamethrower",
			type : "Fire",
			category : "Special",
			power : "90",
			accuracy : "100",
			pp : "15",
			effects : {
				condition : ["Burn"],
				percentage : ["10"],
				increase : [null],
			},
			pokemon : ["ninetales"],
		},
		extrasensory : {
			name : "Extrasensory",
			type : "Psychic",
			category : "Special",
			power : "80",
			accuracy : "100",
			pp : "20",
			effects : {
				condition : ["Flinch"],
				percentage : ["10"],
				increase : [null],
			},
			pokemon : ["ninetales"],	
		},
		heatWave : {
			name : "Heat Wave",
			type : "Fire",
			category : "Special",
			power : "95",
			accuracy : "90",
			pp : "10",
			effects : {
				condition : ["Burn"],
				percentage : ["10"],
				increase : [null],
			},
			pokemon : ["ninetales"],
		},
		confuseRay : {
			name : "Confuse Ray",
			type : "Ghost",
			category : "Status",
			power : "",
			accuracy : "100",
			pp : "10",
			effects : {
				condition : ["Confusion"],
				percentage : ["100"],
				increase : [null],
			},
			pokemon : ["ninetales"],
		},
		imprison : {
			name : "Imprison",
			type : "Psychic",
			category : "Status",
			power : "",
			accuracy : "",
			pp : "10",
			effects : {
				condition : [],
				percentage : [],
				increase : [],
			},
			pokemon : ["ninetales"],
		},
		nastyPlot : {
			name : "Nasty Plot",
			type : "Dark",
			category : "Status",
			power : "",
			accuracy : "",
			pp : "20",
			effects : {
				condition : [{stat:"Special Attack",dir:"+",num:"2"}],
				percentage : [null],
				increase : [null],
			},
			pokemon : ["ninetales"],
		},
		quickAttack : {
			name : "Quick Attack",
			type : "Normal",
			category : "Physical",
			power : "40",
			accuracy : "100",
			pp : "30",
			effects : {
				condition : ["Priority"],
				percentage : [null],
				increase : ["+1"],
			},
			pokemon : ["ninetales"],
		},
		safeguard : {
			name : "Safeguard",
			type : "Normal",
			category : "Status",
			power : "",
			accuracy : "",
			pp : "25",
			effects : {
				condition : [],
				percentage : [],
				increase : [],
			},
			pokemon : ["ninetales"],
		},
	}

	root.dev = dev;
})(this);